const sub_img = [
    {
        id: 'sub_img01',
        image: '/sub_img/standard_01.jpg',
        hover: '/sub_img/standard01_1.jpg',
        title: '바꾸 스탠다드 백',
        price: 15000,
    },
    {
        id: 'sub_img02',
        image: '/sub_img/standard_02.jpg',
        hover: '/sub_img/standard02_1.jpg',
        title: '바꾸 로즈헨',
        price: 15000,
    },
    {
        id: 'sub_img03',
        image: '/sub_img/standard_03.jpg',
        hover: '/sub_img/standard03_1.jpg',
        title: '바꾸 스트로베리',
        price: 15000,
    },
    {
        id: 'sub_img04',
        image: '/sub_img/standard_04.jpg',
        hover: '/sub_img/standard04_1.jpg',
        title: '바꾸 선셋 백',
        price: 15000,
    },
    {
        id: 'sub_img05',
        image: '/sub_img/standard_05.jpg',
        hover: '/sub_img/standard05_1.jpg',
        title: '바꾸 언더 백',
        price: 15000,
    },
    {
        id: 'sub_img06',
        image: '/sub_img/standard_06.jpg',
        hover: '/sub_img/standard06_1.jpg',
        title: '바꾸 리버 베드',
        price: 15000,
    },
    {
        id: 'sub_img07',
        image: '/sub_img/standard_07.jpg',
        hover: '/sub_img/standard07_1.jpg',
        title: '바꾸 플라워 베드',
        price: 15000,
    },
    {
        id: 'sub_img08',
        image: '/sub_img/standard_08.jpg',
        hover: '/sub_img/standard08_1.jpg',
        title: '바꾸 인디고 트리피 체커',
        price: 15000,
    },
    {
        id: 'sub_img09',
        image: '/sub_img/standard_img01.jpg',
        hover: '/sub_img/standard_img01-1.jpg',
        title: '바꾸 스탠다드 백',
        price: 15000,
    },
    {
        id: 'sub_img10',
        image: '/sub_img/standard_img02.jpg',
        hover: '/sub_img/standard_img02-1.jpg',
        title: '바꾸 와일드 선플라워 블루',
        price: 15000,
    },
    {
        id: 'sub_img11',
        image: '/sub_img/standard_img03.jpg',
        hover: '/sub_img/standard_img03-1.jpg',
        title: '바꾸 블루 백',
        price: 15000,
    },
    {
        id: 'sub_img12',
        image: '/sub_img/standard_img04.jpg',
        hover: '/sub_img/standard_img04-1.jpg',
        title: '바꾸 팜베리 백',
        price: 15000,
    },
    {
        id: 'sub_img13',
        image: '/sub_img/standard_img05.jpg',
        hover: '/sub_img/standard_img05-1.jpg',
        title: '바꾸 스탠다드 백',
        price: 15000,
    },
    {
        id: 'sub_img14',
        image: '/sub_img/standard_img06.jpg',
        hover: '/sub_img/standard_img06-1.jpg',
        title: '바꾸 스탠다드 백',
        price: 15000,
    },
    {
        id: 'sub_img15',
        image: '/sub_img/standard_img07.jpg',
        hover: '/sub_img/standard_img07-1.jpg',
        title: '바꾸 스탠다드 백',
        price: 15000,
    },
    {
        id: 'sub_img16',
        image: '/sub_img/standard_img08.jpg',
        hover: '/sub_img/standard_img08-1.jpg',
        title: '바꾸 스탠다드 백',
        price: 15000,
    },
]

export default sub_img